apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-songs-postgresql
  name: {{ .Release.Name }}-songs-postgresql
spec:
  ports:
    - name: tcp-5432
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: {{ .Release.Name }}-songs-postgresql
