apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: songs-postgresql
    app.openshift.io/runtime: postgresql    
  name: songs-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: songs-postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: songs-postgresql
    spec:
      containers:
        - image: registry.access.redhat.com/rhscl/postgresql-96-rhel7
          imagePullPolicy: Always
          name: songs-postgresql
          livenessProbe:
            exec:
              command:
              - /usr/libexec/check-container
              - --live
            initialDelaySeconds: 120
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
              - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: songs-postgresql
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: songs-postgresql
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: songs-postgresql