apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: songs-postgresql,hits-service
  labels:
    app: songs-service
    app.openshift.io/runtime: spring-boot
  name: songs-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: songs-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: songs-service
        version: v1
    spec:
      containers:
        - image: quay.io/right-lyrics/songs-service:1.3
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: songs-postgresql
                  key: password
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: songs-postgresql
                  key: user
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://songs-postgresql:5432/right-lyrics
            - name: HITS_SERVICE_URL
              value: http://hits-service:8080
          imagePullPolicy: Always
          name: songs-service
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          ports:
            - containerPort: 8080