apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: albums-service
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.wildcardDomain }}
      http:
        paths:
          - path: /api/albums
            pathType: Prefix
            backend:
              service:
                name: albums-service
                port: 
                  number: 8080
