apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-keycloak
  name: {{ .Release.Name }}-keycloak
spec:
  ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}-keycloak