apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: hook-succeeded
  name: {{ .Release.Name }}-import-data
spec:
  template:
    spec:
      volumes:
        - configMap:
            name: {{ .Release.Name }}-right-lyrics-data
          name: right-lyrics-data
      containers:
        - name: import
          image: registry.access.redhat.com/ubi8
          command: ["/bin/sh"]
          args: ["-c", "sleep 60; curl -v -F uploadedFile=@/tmp/data.yaml http://{{ .Release.Name }}-import-service:8080/api/import/upload"]
          volumeMounts:
            - mountPath: /tmp/data.yaml
              name: right-lyrics-data
              subPath: data.yaml
      restartPolicy: Never

