apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-import-job
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app.openshift.io/runtime: golang
spec:
  template:
    spec:
      volumes:
        - configMap:
            name: {{ .Release.Name }}-data
          name: data
      containers:
        - name: import
          image: quay.io/right-lyrics/import-job:1.0
          env:
            - name: DATA_FILE
              value: /tmp/data.yaml
            - name: ALBUMS_SERVICE
              value: http://albums-service-{{ .Release.Name }}.{{ .Values.wildcardDomain }}
            - name: LYRICS_SERVICE
              value: http://lyrics-service-{{ .Release.Name }}.{{ .Values.wildcardDomain }}
            - name: SONGS_SERVICE
              value: http://songs-service-{{ .Release.Name }}.{{ .Values.wildcardDomain }}
          volumeMounts:
            - mountPath: /tmp/data.yaml
              name: data
              subPath: data.yaml
      restartPolicy: Never