apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-import-job
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app.openshift.io/runtime: golang
spec:
  template:
    spec:
      volumes:
        - configMap:
            name: {{ .Release.Name }}-data
          name: data
      containers:
        - name: import
          image: quay.io/right-lyrics/import-job:1.0
          imagePullPolicy: Always
          env:
            - name: DATA_FILE
              value: /tmp/data.yaml
            - name: ALBUMS_SERVICE
              value: http://{{ .Release.Name }}-albums-service:8080
            - name: LYRICS_SERVICE
              value: http://{{ .Release.Name }}-lyrics-service:8080
            - name: SONGS_SERVICE
              value: http://{{ .Release.Name }}-songs-service:8080
          volumeMounts:
            - mountPath: /tmp/data.yaml
              name: data
              subPath: data.yaml
      restartPolicy: Never