apiVersion: v1
kind: ConfigMap
metadata:
  name: lyrics-page
data:
  config.js: |
    window.SONGS_SERVICE = "http://{{ .Release.Name }}.{{ .Values.wildcardDomain }}/api/songs/";
    window.LYRICS_SERVICE = "http://{{ .Release.Name }}.{{ .Values.wildcardDomain }}/api/lyrics/";
    window.ALBUMS_SERVICE = "http://{{ .Release.Name }}.{{ .Values.wildcardDomain }}/api/albums/";