apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: songs-service,lyrics-service,albums-service
  labels:
    app: lyrics-page
    app.openshift.io/runtime: nodejs
  name: lyrics-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lyrics-page
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: lyrics-page
    spec:
      volumes:
        - configMap:
            name: lyrics-page
          name: lyrics-page
      containers:
        - image: quay.io/right-lyrics/lyrics-page:1.5
          imagePullPolicy: Always
          name: lyrics-page
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          env:
            - name: NPM_RUN
              value: serve
          volumeMounts:
            - mountPath: /opt/app-root/src/build/config.js
              name: lyrics-page
              subPath: config.js
          ports:
            - containerPort: 8080
