apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-lyrics-page
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.wildcardDomain }}
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: {{ .Release.Name }}-lyrics-page
                port: 
                  number: 8080
