apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lyrics-service
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.wildcardDomain }}
      http:
        paths:
          - path: /api/lyrics
            pathType: Prefix
            backend:
              service:
                name: lyrics-service
                port: 
                  number: 8080
