apiVersion: v1
kind: Service
metadata:
  labels:
    app: lyrics-mongodb
  name: lyrics-mongodb
spec:
  ports:
    - name: tcp-27017
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: lyrics-mongodb
